params:
  busco:
    lineage: bacteria_odb10
  fastp:
    qualified_quality_phred: 15
  flye:
    iterations: 1
  quast:
    min_contig: 500
resources:
  mem_mb: 8192
  threads: 4
run_id: 273b1c6a-3f3e-4165-bade-2c33184d6118
samples:
- expected_genome_size: 5m
  long_reads: null
  organism_type: bacterial
  read1: data/raw/Pn01_R1.fastq.gz
  read2: data/raw/Pn01_R2.fastq.gz
  read_type: short
  sample_id: sample_01
