params:
  busco:
    lineage: bacteria_odb10
  fastp:
    qualified_quality_phred: 15
  flye:
    iterations: 1
  quast:
    min_contig: 500
resources:
  mem_mb: 8192
  threads: 4
run_id: 633eba4e-07ee-40ce-a759-0c3f57d52a4e
samples:
- expected_genome_size: 5m
  long_reads: null
  organism_type: !!python/object/apply:api.models.schemas.OrganismType
  - bacterial
  read1: data/raw\Pn01_R1.fastq.gz
  read2: data/raw\Pn01_R2.fastq.gz
  read_type: !!python/object/apply:api.models.schemas.ReadType
  - short
  sample_id: sample_01
