params:
  busco:
    lineage: bacteria_odb10
  fastp:
    qualified_quality_phred: 15
  flye:
    iterations: 1
  quast:
    min_contig: 500
resources:
  mem_mb: 8192
  threads: 4
run_id: a9d28776-2b83-4d74-a35e-3a371251d6a5
samples:
- expected_genome_size: 5m
  long_reads: null
  organism_type: bacterial
  read1: data/raw/Pn01_R1.fastq.gz
  read2: data/raw/Pn01_R2.fastq.gz
  read_type: short
  sample_id: sample_01hgj
